# Generated by Django 3.2.12 on 2022-04-10 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj_planner_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proj_planner_app.team'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proj_planner_app.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proj_planner_app.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proj_planner_app.team'),
        ),
    ]
