# Generated by Django 3.2.12 on 2022-04-11 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj_planner_app', '0002_auto_20220410_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user_id',
            new_name='team_id',
        ),
        migrations.RemoveField(
            model_name='board',
            name='team_id',
        ),
        migrations.AddField(
            model_name='board',
            name='president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proj_planner_app.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='board_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proj_planner_app.board'),
        ),
    ]
